import { writeFile } from 'node:fs/promises';
import { CURATED_MOVIES } from '../src/app/core/data-access/movie/data/movie-data';
import { VERIFIED_POSTERS } from '../src/app/core/data-access/movie/data/movie-posters';
import { SERIES_ARTWORK } from '../src/app/core/data-access/movie/data/series-artwork';
import { isMoviePosterUrl } from '../src/app/core/models/movie';
import { MoviePosterCatalog } from '../src/server/movie-posters';

function snapshot(name: string, values: Record<string, string>, checkedAt: string | null): string {
  return [
    '/**',
    ` * Wikimedia artwork snapshot checked ${checkedAt}.`,
    ' * Generated by npm run movies:refresh-posters. Review changes before publishing.',
    ' * Artwork rights belong to their respective owners; some series use archived title cards.',
    ' */',
    `export const ${name}: Readonly<Record<string, string>> = {`,
    ...Object.entries(values)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([title, url]) => `  ${JSON.stringify(title)}: ${JSON.stringify(url)},`),
    '};',
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const result = await new MoviePosterCatalog(CURATED_MOVIES).get();
  if (result.source !== 'live') {
    throw new Error(
      'Poster provider unavailable or incomplete. Existing snapshots were NOT changed. Try again later.',
    );
  }
  const filmPosters: Record<string, string> = { ...VERIFIED_POSTERS };
  const seriesArt: Record<string, string> = { ...SERIES_ARTWORK };
  let changed = 0;
  for (const movie of CURATED_MOVIES) {
    if (movie.posterRefresh === false) continue;
    const title = movie.posterPageTitle ?? movie.wikipediaTitle;
    const url = result.posters[movie.slug];
    // Studio/TVmaze fallbacks are not Wikimedia lookup results. Keep their curated maps separate.
    if (!isMoviePosterUrl(url)) continue;
    const target =
      Object.hasOwn(filmPosters, title) || movie.kind === 'film' ? filmPosters : seriesArt;
    if (url !== target[title]) changed++;
    target[title] = url;
  }
  await Promise.all([
    writeFile(
      new URL('../src/app/core/data-access/movie/data/movie-posters.ts', import.meta.url),
      snapshot('VERIFIED_POSTERS', filmPosters, result.checkedAt),
    ),
    writeFile(
      new URL('../src/app/core/data-access/movie/data/series-artwork.ts', import.meta.url),
      snapshot('SERIES_ARTWORK', seriesArt, result.checkedAt),
    ),
  ]);
  console.log(
    `Checked ${CURATED_MOVIES.length} titles; ${changed} artwork URLs changed. Credits and catalog scope were not modified.`,
  );
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
