import { writeFile } from 'node:fs/promises';
import { CURATED_MOVIES } from '../src/app/core/data-access/movie/data/movie-data';
import { VERIFIED_POSTERS } from '../src/app/core/data-access/movie/data/movie-posters';
import { MoviePosterCatalog } from '../src/server/movie-posters';

async function main(): Promise<void> {
  const result = await new MoviePosterCatalog(CURATED_MOVIES).get();
  if (result.source !== 'live') {
    throw new Error(
      'Poster provider unavailable or incomplete. Existing snapshot was NOT changed. Try again later.',
    );
  }
  const posters: Record<string, string> = { ...VERIFIED_POSTERS };
  let changed = 0;
  for (const movie of CURATED_MOVIES) {
    const title = movie.posterPageTitle ?? movie.wikipediaTitle;
    const url = result.posters[movie.slug];
    if (url !== posters[title]) changed++;
    posters[title] = url;
  }
  const content = [
    '/**',
    ` * Wikimedia poster snapshot checked ${result.checkedAt}.`,
    ' * Generated by npm run movies:refresh-posters. Review artwork changes before publishing.',
    ' * Poster rights belong to their respective owners; metadata sources are linked per movie.',
    ' */',
    'export const VERIFIED_POSTERS: Readonly<Record<string, string>> = {',
    ...Object.entries(posters)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([title, url]) => `  ${JSON.stringify(title)}: ${JSON.stringify(url)},`),
    '};',
    '',
  ].join('\n');
  await writeFile(
    new URL('../src/app/core/data-access/movie/data/movie-posters.ts', import.meta.url),
    content,
  );
  console.log(
    `Checked ${CURATED_MOVIES.length} titles; ${changed} poster URLs changed. Credits and catalog scope were not modified.`,
  );
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
